### ISSUE TITLE
spreadsheet with the conference data

### ISSUE THREAD

**Issue by Ricardosgeral** [conference-websites/MobiHoc-2019#1]
hi.
great job with the site.

i'm trying to do something similar, but i'm having some trouble understanding the structure of the google sheets structure.

can you give just the headers of the spreadsheet that has the program?

thanks in advance

**Comment by cawka** [comment]
The sheet ID is configured in _config.yml. You can see the working example here:  https://docs.google.com/spreadsheets/d/1qzsK27dGioaDXXW0BElQiROY2E4cOf9pxAr32tbPEnw

**Comment by Ricardosgeral** [comment]
Thanks Alex

**Comment by cawka** [comment]
You can check also the last year's site. In that one I also had "program-at-glance" generation from another spreadsheet (also linked in `_config.yml`).  In case you want to do something similar.
